ShoeShop/Controllers/PageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShoeShop.Controllers
{
    public class PageController : Controller
    {
        
        // GET: Page
        public ActionResult Index()
        {
            return View();
        }
       
    }
}

ShoeShop/Areas/admin/Views/Page/Create.cshtml
@model Models.EF.Page
@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/admin/Views/Shared/_Layout.cshtml";
}
@section Scriptfooter {
    <script>
    function Browser(){
        var finder = new CKFinder();
        finder.SelectFunction = SetFileField;
        finder.Popup;
    }
    function SetFileField(fileUrl) {
        alert("ad");
        document.getElementById('Image').value = fileUrl;
    }
    </script>
}
<div class="row">
    <div class="col-md-9">
        <h2>Thêm mới Page</h2>
    </div>
    <div class="col-md-3">
        <h2>@Html.ActionLink("Trở về", "Index", "Page", new { @class = "btn btn-info" })</h2>
    </div>
</div>
@using (Html.BeginForm("Create", "Page", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal" role="form">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>     
   
        <div class="form-group">
            @Html.LabelFor(model => model.Postdate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Postdate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Postdate, "", new { @class = "text-danger" })
            </div>
        </div>  
        <div class="form-group">
            @Html.LabelFor(model => model.Author, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Author, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Author, "", new { @class = "text-danger" })
            </div>
        </div>  
        <div class="form-group">
            @Html.LabelFor(model => model.PageContent, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.PageContent, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PageContent, "", new { @class = "text-danger" })
            </div>
        </div>     
        </div>
        <div class="form-group" style="padding-top: 10px;">
            <div class="col-md-offset-2 col-md-6">
                <input type="submit" value="Thêm mới" class="btn btn-success" />
                <input type="reset" class="btn btn-warning" value="Hủy" />
            </div>
    </div>
            }


ShoeShop/Areas/admin/Views/Page/Delete.cshtml

@model Models.EF.Page

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/admin/Views/Shared/_Layout.cshtml";
}

<h2>Xóa</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Page</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Postdate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Postdate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Author)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Author)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PageContent)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PageContent)
        </dd>    
    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ShoeShop/Areas/admin/Views/Page/Edit.cshtml
@model Models.EF.Page

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/admin/Views/Shared/_Layout.cshtml";
}

<h2>Chỉnh sửa</h2>

@using (Html.BeginForm("Edit", "Page", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Page</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Postdate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Postdate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Postdate, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Author, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Author, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Author, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.PageContent, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.PageContent, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PageContent, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group" style="padding-top: 10px;">
            <div class="col-md-offset-2 col-md-6">
                <input type="submit" value="Lưu " class="btn btn-success" />
                <input type="reset" class="btn btn-warning" value="Hủy" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ShoeShop/Areas/admin/Views/Page/Index.cshtml
 @{
    ViewBag.Title = "Index";
    Layout = "~/Areas/admin/Views/Shared/_Layout.cshtml";
}
@model PagedList.IPagedList<Models.EF.Page>
@using PagedList.Mvc;
<script src="~/Assets/admin/bower_components/jquery/dist/jquery.min.js"></script>
<script>
    $(document).ready(function() {
        $('#ck_allCheck').click(function(event) {  //on click
            if(this.checked) { // check select status
                $('.checkbox1').each(function() { //loop through each checkbox
                    this.checked = true;  //select all checkboxes with class "checkbox1"
                });
            }else{
                $('.checkbox1').each(function() { //loop through each checkbox
                    this.checked = false; //deselect all checkboxes with class "checkbox1"
                });
            }
        });

        $("#delete").click(function () {
            var selectedIDs = new Array();
            $('input:checkbox.checkbox1').each(function () {
                if ($(this).prop('checked')) {
                    selectedIDs.push($(this).val());
                }
            });

            var options = {};
            options.url = "/Page/Delete";
            options.type = "POST";
            options.data = JSON.stringify(selectedIDs);
            options.contentType = "application/json";
            options.dataType = "json";
            options.success = function (msg) {
                alert(msg);
            };
            if (confirm("Bạn có thực sự muốn xóa những Page đã chọn không?")) {
                $.ajax(options);
            }
            for (var i = 0; i < selectedIDs.length; i++) {
                $("#row_" + selectedIDs[i]).remove();
            }
        });
    });
</script>
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Quản lý Page @Html.ActionLink("Thêm Page  mới", "Create", "Page", new {@class="btn btn-success" })</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="row" style="padding-bottom: 20px;">
                    <div class="top-tbl-page">
                        <div class="col-md-4">
                            <button id="delete" class="btn btn-danger">Xóa Page đã chọn</button>
                        </div>
                        <div class="col-sm-8">
                            @using (Html.BeginForm("Index", "Page", FormMethod.Get))
                            {
                                    <div class="col-md-4"></div>
                                    <div class="col-md-6 text-right" style="padding-right: 0px;">
                                        <input type="text" class="form-control" name="searchKey" />
                                    </div>
                                    <div class="col-sm-2"  style="padding-left: 0px;">
                                        <input type="submit" class="btn btn-primary" value="Tìm kiếm" />
                                    </div>
                              }
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="dataTable_wrapper">
                    <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                        <thead>
                            <tr>
                                <th class="text-center"><input class="form-control" type="checkbox" name="ck_allCheck" id="ck_allCheck" /></th>
                                <th class="text-center">STT</th>
                                <th class="text-center">Title </th>  
                                <th class="text-center">PostDate</th>
                                <th class="text-center">Author</th>
                                <th class="text-center">PageContent</th>
                            </tr>
                        </thead>
                        <tbody class="text-center">
                            @{int i = 0;}
                            @if (Model != null)
                            {
                                foreach (var item in Model)
                                {
                                    i++;
                                    <tr class="odd gradeX" id="row_@item.ID">
                                        <td style="width: 40px;"><input class="form-control checkbox1" type="checkbox" value="@item.ID" /></td>
                                        <td>@i</td>
                                        <td>
                                            <div class="w-100"><a class="btn-link h4 alert-link" href="/admin/Page/Edit/@item.ID">@item.Title</a></div>
                                            <div class="w-100">
                                                <ul>
                                                    <li><a href="/admin/Page/Edit/@item.ID">Chỉnh sửa</a></li>
                                                    <li>|</li>
                                                    <li>
                                                        @Ajax.ActionLink("Xóa", "Delete", new { @id = item.ID }, new AjaxOptions
                                                   {
                                                       Confirm = "Bạn có thực sự muốn xóa không?",
                                                       OnComplete = "$(#row_" + item.ID + "').remove()",
                                                       HttpMethod = "Delete"
                                                   })
                                                <li>|</li>
                                                <li><a href="?atc=see">Xem</a></li>
                                            </ul>
                                        </div>
                                    </td>    
                                        <td>@item.Postdate</td>
                                        <td>@item.Author</td>
                                        <td>@item.PageContent</td>

                                </tr>

                                }
                            }
                            else
                            {
                                <tr><td colspan="4" class="danger">Không có Page nào!</td></tr>
                            }
                        </tbody>
                    </table>
                    @if(Model!=null)
                    {
                        @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))
                    }
                </div>

                <!-- /.table-responsive -->
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->

